import { app, BrowserWindow, globalShortcut, Menu } from "electron";
import path from "path";
import fs from "fs";

let mainWindow: BrowserWindow | null = null;
let serverStarted = false;
let serverPort = 38472;

// Security warnings are intentionally left enabled to ensure safe configurations are maintained

async function createWindow() {
  // Set DATA_DIR before starting the server so the DB is stored in the correct location
  if (app.isPackaged && !process.env.PORTABLE_EXECUTABLE_DIR) {
    process.env.PORTABLE_EXECUTABLE_DIR = path.dirname(app.getPath("exe"));
  }

  const exeDir = process.env.PORTABLE_EXECUTABLE_DIR || process.cwd();
  const configPath = path.join(exeDir, "linkhub.config.json");
  let customDataDir = null;

  if (fs.existsSync(configPath)) {
    try {
      const config = JSON.parse(fs.readFileSync(configPath, "utf-8"));
      if (config.dataDir) {
        customDataDir = config.dataDir;
      }
    } catch (e) {
      console.error("Failed to read config:", e);
    }
  }

  if (!process.env.DATA_DIR) {
    if (customDataDir) {
      process.env.DATA_DIR = customDataDir;
    } else if (app.isPackaged) {
      // In production, store data next to the executable (portable mode)
      process.env.DATA_DIR = path.join(exeDir, "data");
    } else {
      // In development, store in the project root
      process.env.DATA_DIR = path.join(process.cwd(), "data");
    }
  }

  // Determine icon path (dist in prod, public in dev)
  let iconPath = path.join(__dirname, "../dist/icon.png");
  if (!fs.existsSync(iconPath)) {
    iconPath = path.join(__dirname, "../public/icon.png");
  }

  mainWindow = new BrowserWindow({
    width: 1200,
    height: 800,
    title: "LinkHub",
    autoHideMenuBar: true, // Hide the top menu bar
    icon: iconPath,
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
    },
  });

  // Ensure menu bar is completely removed
  mainWindow.setMenuBarVisibility(false);
  mainWindow.setMenu(null);

function escapeHtml(unsafe: string): string {
  return unsafe
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

   // Start the Express server only once, and ONLY in production
   // In development, npm run dev starts the server in Node.js to avoid native module ABI mismatches
    if (app.isPackaged && !serverStarted) {
      try {
       // @ts-ignore - server.js is generated by tsup in the same output directory
       const { startServer } = await import("./server.js");
       serverPort = await startServer(true);
       serverStarted = true;
     } catch (e: any) {
       console.error("Failed to start server:", e);
       mainWindow.loadURL(`data:text/html;charset=utf-8,
         <html>
           <body style="font-family: sans-serif; padding: 2rem; text-align: center; background: #f8f9fa; color: #333;">
             <h1 style="color: #e11d48;">Fatal Error: Server Failed to Start</h1>
             <p>The internal server encountered an error and could not start.</p>
             <p>Error details: ${escapeHtml(e.message || String(e))}</p>
             <p>Press <b>F12</b> to open Developer Tools and check the console.</p>
           </body>
         </html>
       `);
       return;
     }
   } else if (!app.isPackaged && !serverStarted) {
    // In development, npm run dev starts the server.
    // Read the actual port from the port file written by the server.
    const portFile = path.join(process.cwd(), ".server-port");
    try {
      const portStr = fs.readFileSync(portFile, "utf-8").trim();
      serverPort = parseInt(portStr, 10);
      console.log("Dev server port from file:", serverPort);
    } catch {
      // Fall back to default port if file doesn't exist yet
      serverPort = 3070;
      console.log("Port file not found, falling back to default port 3070");
    }
    serverStarted = true;
  }

  // Load the web app (with retry in dev mode for server startup race)
  const appUrl = `http://127.0.0.1:${serverPort}`;
  console.log("Loading app from:", appUrl);

  const loadWithRetry = async (retries = 10, delay = 1000) => {
    for (let i = 0; i < retries; i++) {
      try {
        const resp = await fetch(appUrl, { method: "HEAD" });
        if (resp.ok || resp.status < 500) {
          mainWindow?.loadURL(appUrl);
          return;
        }
      } catch {}
      console.log(`Server not ready yet, retrying (${i + 1}/${retries})...`);
      await new Promise(r => setTimeout(r, delay));
    }
    mainWindow?.loadURL(appUrl);
  };

  if (!app.isPackaged) {
    loadWithRetry();
  } else {
    mainWindow.loadURL(appUrl);
  }

  if (!app.isPackaged) {
    mainWindow.webContents.openDevTools();
  }

  mainWindow.webContents.on('context-menu', (e, props) => {
    const menu = Menu.buildFromTemplate([
     {
       label: 'Inspect Element',
       click: () => {
         mainWindow?.webContents.inspectElement(props.x, props.y);
       }
     },
     {
       label: 'Toggle Developer Tools',
       click: () => {
         mainWindow?.webContents.toggleDevTools();
       }
     },
     {
       label: 'Reload',
       click: () => {
         mainWindow?.webContents.reload();
       }
     }
   ]);
   menu.popup();
  });

  mainWindow.webContents.on('did-fail-load', (event, errorCode, errorDescription) => {
    if (errorCode === -3) return; // ERR_ABORTED — normal on HMR reload, refresh, or close
    console.error('Failed to load:', errorCode, errorDescription);
    if (mainWindow) {
      mainWindow.loadURL(`data:text/html;charset=utf-8,
        <html>
          <body style="font-family: sans-serif; padding: 2rem; text-align: center; background: #f8f9fa; color: #333;">
            <h1 style="color: #e11d48;">Failed to connect to local server</h1>
            <p>Error: ${errorCode} (${escapeHtml(errorDescription)})</p>
            <p>The local server might have crashed or failed to start.</p>
            <p>Press <b>F12</b> to open Developer Tools and check the console.</p>
          </body>
        </html>
      `);
    }
  });

  mainWindow.webContents.on('render-process-gone', (event, details) => {
    console.error('WebContents crashed or was killed:', details.reason);
  });

  mainWindow.on("closed", () => {
    mainWindow = null;
  });
}

app.whenReady().then(() => {
  // Single instance lock - focus existing window if another instance is launched
  const gotLock = app.requestSingleInstanceLock();

  if (!gotLock) {
    app.quit();
    return;
  }

  app.on("second-instance", () => {
    if (mainWindow) {
      if (mainWindow.isMinimized()) mainWindow.restore();
      mainWindow.focus();
    }
  });

  createWindow();
  globalShortcut.register('CommandOrControl+Shift+I', () => mainWindow?.webContents.toggleDevTools());
  globalShortcut.register('F12', () => mainWindow?.webContents.toggleDevTools());
});

app.on("will-quit", () => {
  globalShortcut.unregisterAll();
});

app.on("window-all-closed", () => {
  if (process.platform !== "darwin") app.quit();
});

app.on("activate", () => {
  if (mainWindow === null) createWindow();
});
